config/routes.rb
Rails.application.routes.draw do
 

  mount Ckeditor::Engine => '/ckeditor'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'projects/index'

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }
  #devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  
  resources :projects do
    resources :sprints, :only => [:index,:show ,:new,:create ,:edit, :update, :destroy] do
      resources :tasks,:only => [:index,:show ,:new,:create ,:edit, :update, :destroy]
    end
  end
  put "/projects/:project_id/sprints/:sprint_id/tasks" => "tasks#change_stage"
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :project
  belongs_to :sprint
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  #before_action :find_project
  before_action :find_task ,only: [:edit, :update, :show, :delete]
  before_action :find_sprint, only: [:edit, :update, :destroy]
  
  def index
    @sprint = Sprint.find(params[:sprint_id])
    #@task = Task.find(params[:id])
    @tasks =  @sprint.tasks
  end

  def new
    @task = Task.new
    @sprint = Sprint.find(params[:sprint_id])
    @project = Project.find(params[:project_id])
  end

  def create
    @project = Project.find(params[:project_id])
    @sprint = @project.sprints.find(params[:sprint_id])
    @task = @sprint.tasks.create(task_params)
    @task.user_id = current_user.id
    @task.project_id = @project.id
    if @task.save
    	redirect_to project_sprint_tasks_path(@task)
    else
      render 'new'
    end
  end
  
  def edit
    @project = Project.find(params[:project_id])
    @sprint = @project.sprints.find(params[:sprint_id])
  end

  def update
    if @task.update(task_params)
      redirect_to project_sprint_task_path(@task)
      flash[:notice] = "Successfully updated task!"
    else
      render :edit
      flash[:alert] = "Error updating task!"
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to project_sprint_task_path(@sprint)
    flash[:notice] = "Successfully deleted task!"
  end 

  def change_stage
    task_state = params[:state_task]
    container_stage = params[:container_stage]

    puts task_state.inspect
    @sprint = Sprint.find(params[:sprint_id])
    @task = @sprint.tasks.find(params[:id])
    if container_stage == '3'
      @task.update_attributes(:state_task => task_state, :done_time => Time.now)
    else
      @task.update_attributes(:state_task => task_state, :done_time => 0)
    end
  end 

  private

  def task_params
    params.require(:task).permit(:name, :type_task, :user_id, :project_id,:sprint_id, :dev_start_time, :dev_end_time, :state_task, :to_do_start_time, :to_do_end_time, :done_time)
  end

  def find_project
    @project = Project.find(params[:project_id])    
  end

  def find_sprint
    @sprint = Sprint.find(params[:sprint_id])    
  end	

  def find_task
  	@task = Task.find(params[:id])    
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class="col-md-12">
  <%= simple_form_for  [@project, @sprint ,@sprint.tasks.new] do |f| %>
    <div class="glyphicon glyphicon-remove-circle close-forms"></div>  
    
    <div class="form-group">
      <%= f.input :name, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.input :state_task, :collection => { 'TO-DO'=> 0,'DEV'=> 1,'QA'=> 2, 'DONE'=> 3}, :multiple => true, class: "form-control" %>
    </div>
   
    <div class="form-group">
      <%= f.input :type_task, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.hidden_field :to_do_start_time, value: Time.now  %>
    </div>

    <div class="form-group">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>
<script type="text/javascript">
  $('.close-forms').click(function(){
    $('#form-sprints').css({'display':'none'});
  })
</script>

app/views/tasks/_tasks.html.erb
<h1><%=@sprint.name%> | Planning board</h1>
<div class="col-md-6 col-sm-6 col-xs-12">
<% @days_done ||= []%>
<%
        start = @sprint.begin_sprint.to_datetime
        finish = @sprint.end_sprint.to_datetime
        @arrayOfdays1 = (start..finish).map do |days|
          days.strftime("%e").to_i
        end
      %>
  <% @sprint.tasks.each do |task|%>
    <div class="col-md-12 col-sm-12 col-xs-12">
      <%= task.name %>
      <%task.id %>
      <%
        if defined?(task.done_time) && (task.done_time != nil) && (task.done_time != 0)
          task.done_time.strftime("%e") 
        end
       %>
      <%if task.project && task.id %>
      <%= link_to 'Edit', edit_project_sprint_task_path(task.project_id,task.sprint_id, task.id)%>
      <%#= link_to 'Show', project_sprint_path(sprint.project_id , sprint.id)%>
      <%#= link_to 'Delete', project_sprint_task_path(:id=> task.id), :method => :delete %>
      <%#= link_to 'Edit', [:edit, @sprint.tasks, @task] %>
      <%end%>
      <%
      if defined?(task.done_time) && (task.done_time != nil) && (task.done_time != 0)
      @task_day_done = task.done_time.strftime("%e").to_i
      @days_done.push(@task_day_done)
      end 

      
      %>

    </div>
  <%end%>
   <% @days_done %>
      <% @arrayOfdays1 %>
      <% 
      
      #(@days_done - @arrayOfdays1).empty? # => true
      #@days_done.all?{|i| @arrayOfdays1.include? i }
      b = Hash.new(0)

      # iterate over the array, counting duplicate entries
     

      @days_done.each do |v|
       b[v] += 1
      end
     
      %>
<% @arrayNewRepeat ||= []
      b.each do |k, v|
       @arrayNewRepeat.push([k,v])
      end
%>
<%=@arrayNewRepeat %>
<%
@arrayNewEmpty ||= []

#for i in 0..@arrayOfdays1.size
 # @arrayNewEmpty.push(0)
#end

@arrayNewRepeat.each_with_index do |x, index|
  x.each do |y|
   @arrayNewEmpty.push(x)
  end
  
  
end
@arrayOfdays1.each do |x|
   @arrayNewEmpty.push(x)  
end


%>
<%#= @arrayMerge= @arrayOfdays1.zip(@arrayNewEmpty) %>
<%= @arrayOfdays1%>
<%= @arrayNewEmpty%>




</div>

<div class="row">

<div id="board" class="col-md-12">
<h3>Board </h3>
  <div class="row">
  
     <div class="col-md-3">ToDo</div><div class="col-md-3">In Progress</div><div class="col-md-3">QA</div> <div class="col-md-3">Done</div>
  
    <ul id="0" class="container-stages col-md-3">
      <% @sprint.tasks.each do |task|%>
        <% if task.state_task == '0'%>
          <li id='<%= task.id %>'  class="li-task" draggable="true" data-remote="true">
            <%= task.name %>
            <%= task.type_task %>
          </li>
        <%end%>
      <%end%>
    </ul>
    <ul id="1" class="container-stages col-md-3">
      <% @sprint.tasks.each do |task|%>
        <% if task.state_task == '1'%>
          <li id='<%= task.id %>'  class="li-task" draggable="true" data-remote="true">
            <%= task.name %>
            <%= task.type_task %>
          </li>
        <%end%>
      <%end%> 
    </ul>
    <ul id="2" class="container-stages col-md-3">
      <% @sprint.tasks.each do |task|%>
        <% if task.state_task == '2'%>
          <li id='<%= task.id %>'  class="li-task" draggable="true" data-remote="true">
            <%= task.name %>
            <%= task.type_task %>
          </li>
        <%end%>
      <%end%>
    </ul>
    <ul id="3" class="container-stages col-md-3">
      <% @sprint.tasks.each do |task|%>
        <% if task.state_task == '3'%>
          <li id='<%= task.id %>'  class="li-task" draggable="true" data-remote="true">
            <%= task.name %>
            <%= task.type_task %>
          </li>
        <%end%>
      <%end%>
    </ul>
  </div>
</div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    var stage_id;
    var task_id;
    var container_stage;

    $('li').bind('dragstart', function(event) {
      event.originalEvent.dataTransfer.setData("text/plain",  event.target.getAttribute('id'));
      task_id = $(event.target).attr('id');
    });

    $('ul').bind('dragover', function(event) {
      event.preventDefault();
    });

    $('ul').bind('dragenter', function(event) {
      $(this).addClass("over");
    });

    $('ul').bind('dragleave drop', function(event) {
      stage_id = $(event.target).attr('id');

      $(this).removeClass("over");
    });

    $('li').bind('drop', function(event) {
      return false;
    });

    $('ul').bind('drop', function(event) {
      var listitem = event.originalEvent.dataTransfer.getData("text/plain");
      event.target.appendChild(document.getElementById(listitem));
      container_stage = $(this).attr('id');
      $(this).children().attr('container-stage',container_stage);
      changeStage();
      event.preventDefault();
    });

    function changeStage(){
      data_send = { id: task_id,state_task:stage_id, container_stage: container_stage }
      var url = "/projects/5/sprints/43/tasks#change_stage"
      $.ajax({
        method: 'put',
        url: url,
        dataType: 'html',
        data: data_send,
          success: function(data) {
           //console.log(data)
        }
      });
    }
  });
</script>
       
   
 

app/views/tasks/create.html.erb
<h1>Sprints#create</h1>
<p>Find me in app/views/sprints/create.html.erb</p>

app/views/tasks/create.js.erb
$('#sprint-list').append("<%= render 'sprints'%>");

app/views/tasks/destroy.html.erb
<h1>Sprints#destroy</h1>
<p>Find me in app/views/sprints/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Tasks#edit</h1>
 <%= simple_form_for ([@project, @sprint, @task]) do |f| %>
    
  
  <div class="form-group">
    <%= f.input :name, value:'Sprint', class: "form-control" %>
  </div>
   <div class="form-group">
    <%= f.input :state_task, :collection => { 'NEW'=> 0,'DEV'=> 1,'QA'=> 2, 'END'=> 3}, :multiple => true, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.input :type_task, class: "form-control" %>
  </div>
   
  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

</div>

app/views/tasks/index.html.erb
<%= render "tasks/tasks" %>

app/views/tasks/new.html.erb
<div class="container">
  <h1>Task#new</h1>
  <%= render "form" %>
</div>

app/views/tasks/show.html.erb
<div class="col-md-12 col-sm-12 colcol-xs-12 blog-content">
  <div class=""><%= @task.name %></div>
  <div class=""><%= @task.type_task %></div>
  <div class="">
  <%= if @task.state_task == '0'
  		@task.state_task = 'DEV'
  	  elsif @task.state_task == '1'
  	    @task.state_task = 'QA'
  	  else 	
  	  	@task.state_task = 'FINISHED'
  	  end
  %>
   	
  </div>
  <% if user_signed_in? %>
    <div class="links-show">
      
    </div>
  <% end %>
  
 

</div>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>