config/routes.rb
Rails.application.routes.draw do
 

  mount Ckeditor::Engine => '/ckeditor'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'projects/index'

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }
  #devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  
  resources :projects do
    resources :sprints, :only => [:index,:show ,:new,:create ,:edit, :update, :destroy] do
      resources :tasks,:only => [:index,:show ,:new,:create ,:edit, :update, :destroy]
    end
  end
  put "/projects/:project_id/sprints/:sprint_id/tasks" => "tasks#change_stage"
end

app/models/sprint.rb
class Sprint < ApplicationRecord
  belongs_to :user
  belongs_to :project
  has_many :tasks, :dependent => :destroy
end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController
  before_action :find_project
  before_action :find_sprint, only: [:destroy, :edit, :update]
  
  def index
  end

  def create
    @project = Project.find(params[:project_id])
    @sprint = @project.sprints.create(sprint_params)
    @sprint.user_id = current_user.id
    if @sprint.save
      @sprints = Sprint.all
      respond_to do |format|
        format.html{redirect_to project_path(@project)}
        format.js#render sprints/create.js.erb
      end
    else
      render 'new'
    end
  end
  
  def edit
    @close_sprint = params[:close_sprint]
    if @close_sprint#change state sprint to closed if you click on closed
      @sprint.state = 1
    end
  end

  def update
    if @sprint.update(sprint_params)
      redirect_to project_path(find_project)
      flash[:notice] = "Successfully updated sprint!"
    else
      render :edit
      flash[:alert] = "Error updating sprint!"
    end
  end

  def show
   
    @sprints = Sprint.all
    @project = Project.find(params[:id])
    @sprint = @project.sprints.find(params[:id])
    @tasks = Task.all      
  end

  def destroy
    @sprint = Sprint.find(params[:id])
    @sprint.destroy
    redirect_to project_path(@project)
    flash[:notice] = "Successfully deleted project!"
  end  

  private

  def sprint_params
    params.require(:sprint).permit(:name, :state, :begin_sprint, :end_sprint, :hours, :number_tasks, :num_compromised_points, :completed_tasks, :completed_points, :defects_found, :owner_sprint)
  end

  def find_project
    @project = Project.find(params[:project_id])    
  end

  def find_sprint
    @sprint = @project.sprints.find(params[:id])    
  end
end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/views/sprints/_form.html.erb
<div class="col-md-12">
  <div class="glyphicon glyphicon-remove-circle close-forms"></div> 
  <%= simple_form_for [@project, @project.sprints.build] , :remote => true do |f| %>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.input :name, value:'Sprint', class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.hidden_field :owner_sprint, value:current_user.email, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.input :state, :collection => { 'ACTIVE' => 0,'CLOSED' => 1, 'PAUSED' => 2}, :multiple => true, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.input :begin_sprint, :order => [:day, :month, :year], :discard_hour => true, :discard_minute => true, class: "form-control" %>
      </div>

       <div class="form-group">
        <%= f.input :end_sprint, :order => [:day, :month, :year], :discard_hour => true, :discard_minute => true,  class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
       <%= f.input :hours, class: "form-control" %>
      </div>

      <div class="form-group">
       <%= f.input :number_tasks, class: "form-control" %>
      </div>

      <div class="form-group">
       <%= f.input :num_compromised_points, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.button :submit %>
      </div>
    </div>
  <% end %>
</div>
<script type="text/javascript">
  $('.close-forms').click(function(){
    
    $('#form-sprints').css({'display':'none'});
  })
</script>

app/views/sprints/_sprints.html.erb
<div class="col-md-6 col-sm-6 col-xs-12">
  <%= link_to 'Add New Sprint', '#', class: 'btn btn-primary', id: 'new_sprint' %>
  <% @sprints.each do |sprint|%>
    <div class="col-md-12 col-sm-12 col-xs-12">
      <%= sprint.name %>
      <%= link_to 'Edit', edit_project_sprint_path(sprint.project_id , sprint.id)%>
      <%= link_to 'Close', edit_project_sprint_path(sprint.project_id , sprint.id,:close_sprint=>'close_sprint')%>
      <%= link_to 'Show', project_sprint_path(sprint.project_id , sprint.id)%>
      <%= link_to 'Delete', project_sprint_path(sprint.project_id , sprint.id), :method => :delete %>
    </div>
<%end%>

 

app/views/sprints/create.js.erb
console.log('HOLA');
$('#sprint-list').html("<%= escape_javascript(render 'sprints') %>");

app/views/sprints/edit.html.erb
<div class="container">
  <h1>Sprints#edit</h1>
 <%= simple_form_for ([@project, @sprint]) do |f| %>
    
<div class="form-group">
    <%= f.input :name, value:'Sprint', class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.hidden_field :owner_sprint, value:current_user.email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.input :state, :collection => {'ACTIVE' => 0, 'CLOSED' => 1, 'PAUSED' => 2}, :multiple => true, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.input :begin_sprint,:order => [:day, :month, :year], :discard_hour => true, :discard_minute => true, class: "form-control" %>
  </div>

   <div class="form-group">
    <%= f.input :end_sprint,:order => [:day, :month, :year], :discard_hour => true, :discard_minute => true, class: "form-control" %>
  </div-->

  <div class="form-group">
   <%= f.input :hours, class: "form-control" %>
  </div>

  <div class="form-group">
   <%= f.input :number_tasks, class: "form-control" %>
  </div>

  <div class="form-group">
   <%= f.input :num_compromised_points, class: "form-control" %>
  </div>
 
  <%if(@close_sprint === 'close_sprint')%>
     
  <div class="form-group">
   <%= f.input :completed_tasks, class: "form-control" %>
  </div>
  <div class="form-group">
   <%= f.input :completed_points, class: "form-control" %>
  </div>
  <div class="form-group">
   <%= f.input :defects_found, class: "form-control" %>
  </div>
 
  <%end%>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

</div>

app/views/sprints/index.html.erb
<h1>Sprints#index</h1>

app/views/sprints/new.html.erb
<div class="container">
  <h1>Sprint#new</h1>
  <%= render "form" %>
</div>

app/views/sprints/show.html.erb
<h2 class="text-center"><%= @sprint.name %></h2>
<%= link_to 'Back', project_path(@sprint.project_id) %>
<div id="tabs-sprints" class="container-fluid"> 
  <ul class="nav nav-tabs">
    <li class="active">
      <a  href="#1" data-toggle="tab">Sprint Overview</a>
      </li>
      <li><a href="#2" data-toggle="tab">Metrics</a>
      </li>
      <li><a href="#3" data-toggle="tab">Sprint Tasks</a>
    </li>
  </ul>

  <div class="tab-content ">
    <div class="tab-pane active" id="1">
      <div class="col-md-12 col-sm-12 colcol-xs-12 blog-content">
        <div class=""><%= @sprint.name %></div>
        <div class=""><%= "Hours: "+ @sprint.hours.to_s %></div>
        <div class=""><%= "Number of Tasks: "+@sprint.number_tasks.to_s %></div>
        <div class=""><%= "Number of Compromised Tasks: "+@sprint.num_compromised_points.to_s %></div>
        <div> <%= "Sprint start: "+@sprint.begin_sprint.strftime("%B %e %Y") %></div>
        <div><%= "Sprint End: "+@sprint.end_sprint.strftime("%B %e %Y") %></div>
        <% @sprint_days = (@sprint.end_sprint - @sprint.begin_sprint).to_i / (24*60*60) %>
        <div class="">
          <%= 
            if @sprint.state == '0'
              @sprint.state = 'Sprint state: ACTIVE'
            elsif @sprint.state == '1'
              @sprint.state = 'Sprint state: CLOSED'
            else  
              @sprint.state = 'Sprint state: PAUSED'
            end
          %>
        </div>
        <%= link_to 'Add New Task', '#', class: 'btn btn-primary', id: 'new_task' %>
        <div id="form-sprints" class="center-div col-md-3 col-sm-3 col-xs-12">
          <%= render 'tasks/form'%>
        </div> 
      </div>
    </div>
    <div class="tab-pane" id="2">
      <%=
        start = @sprint.begin_sprint.to_datetime
        finish = @sprint.end_sprint.to_datetime
        @arrayOfdays = (start..finish).map do |days|
          days.strftime("%e").to_i
        end
      %>
      <%= @tasksnumber = [*1..@sprint.number_tasks.to_i] %>
      

      <div id="sprintChart" class="col-md-12 cols-sm-12 col-xs-12 "></div>
    </div>
    <div class="tab-pane" id="3">
      <%= render :template => "tasks/index" %>
    </div>
  </div>
</div>

<script type="text/javascript">
  var sprint = "<%= @sprint.name %>"
  var arrayDays = <%= @arrayOfdays %>
  var arrayTaskNum = <%= @tasksnumber %>
  
  $(document).ready(function(){
    $( '#new_task' ).click(function(e) {
      e.preventDefault();
      $('#form-sprints').toggle('slow',function(){
      $('#sprint_name').focus();
      });  
    });
    var divWidth = $('.center-div').width();
    var windowWidth = $(window).width();
    $('#form-sprints').css({'left': (windowWidth-divWidth)/2 })
  })
    
  $(function () {
    
      Highcharts.chart('sprintChart', {
          chart: {
              type: 'areaspline'
          },
          title: {
              text: sprint
          },
          legend: {
              layout: 'vertical',
              align: 'left',
              verticalAlign: 'top',
              x: 150,
              y: 100,
              floating: true,
              borderWidth: 1,
              backgroundColor: (Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'
          },
          xAxis: {
              categories: arrayDays,
              /*plotBands: [{ // visualize the weekend
                  from: 4.5,
                  to: 6.5,
                  color: 'rgba(68, 170, 213, .2)'
              }]*/
          },
          yAxis: {
              title: {
                  text: 'Tasks',
                  
              },
              categories: arrayTaskNum
          },
          tooltip: {
              shared: true,
              valueSuffix: ' Tasks'
          },
          credits: {
              enabled: false
          },
          /*plotOptions: {
              areaspline: {
                  fillOpacity: 0.5
              }
          },*/
          series: [
          {
              name: sprint,
              data: [3, 4, 3, 5, 4, 7, 4, 5, 8, 5]
          }
          ]
      });
  });
</script>