config/routes.rb
Rails.application.routes.draw do
 

  mount Ckeditor::Engine => '/ckeditor'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'projects/index'

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }
  #devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  
  resources :projects do
    resources :sprints, :only => [:index,:show ,:new,:create ,:edit, :update, :destroy] do
      resources :tasks,:only => [:index,:show ,:new,:create ,:edit, :update, :destroy]
    end
  end
  put "/projects/:project_id/sprints/:sprint_id/tasks" => "tasks#change_stage"
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :sprints, :dependent => :destroy
  has_many :tasks, :dependent => :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:edit, :update, :show, :delete]
  before_action :authenticate_user!

  def index
    @user = current_user
    @projects =  @user.projects
  end

  def new
    @project = Project.new
  end

  def create
  @project = Project.new(project_params)
  @project.user = current_user
    if @project.save
      redirect_to projects_path(@project)
    else
      render :new
      flash[:alert] = "Error creating new project!"
    end
  end
  
  def edit
    @project = Project.find(params[:id])
  end
 
  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
      redirect_to projects_path(@project)
      flash[:notice] = "Successfully updated project!"
    else
      render :edit
      flash[:alert] = "Error updating project!"
    end
  end
 
  def show
    @project = Project.find(params[:id])
    @sprints = @project.sprints.where(project_id: @project).order("created_at ASC")
  end
 
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = "Successfully deleted project!"
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :owner, :state, :number_sprints, :details, :sprints)
  end

  def find_project
    @project = Project.find(params[:id])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for (@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:" %>
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.hidden_field :owner, value:current_user.email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.input :name, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.input :state, :collection => { 'ACTIVE' => 0,'CLOSED' => 1, 'PAUSED' => 2}, :multiple => true, class: "form-control" %>
  </div>

  <!--div class="form-group">
    <%#= f.input :number_sprints, class: "form-control" %>
  </div-->

   <!--div class="form-group">
    <%#= f.input :sprints, class: "form-control" %>
  </div-->

  <div class="form-group">
    <%= f.input :details, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'basic'}}, class: "form-control", id: "details-project" %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<div class="container">
  <h1>Projects#edit</h1>
  <%= render "form" %>
</div>

app/views/projects/index.html.erb
 

 
   <div id="wrapper">
        
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <a href="#menu-toggle" class="glyphicon glyphicon-chevron-left hide-left-bar" id="menu-toggle" ></a>
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    
                       My Projects
                    
                </li>
                  
                    <% @projects.each do |project| %>
                      <%= link_to  project_path(project) do %>
                        <li>
                          <div class="title_projects"><%= project.name %></div>
                          <div>
                            <%#= strip_tags(raw(project.details).truncate(358)) %>
                          </div>
                          
                          <div class="read-more">
                             
                            <%#= link_to 'Delete', project, :method => :delete%>
                          </div>
                          
                        </li>
                      <% end %>
                    <%end%>               
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                      <% if user_signed_in? %>
                        <div class="link-newProject">
                          <%= link_to 'New Project', new_project_path, class: 'btn btn-primary' %>
                        </div>
                      <% end %>
                        
                        
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>

<script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        if($(this).hasClass('glyphicon-chevron-right')){
          $(this).removeClass('glyphicon-chevron-right').addClass('glyphicon-chevron-left');
        }
        else{
          $(this).removeClass('glyphicon-chevron-left').addClass('glyphicon-chevron-right');  
        }
        $("#wrapper").toggleClass("toggled");
    });
</script>

app/views/projects/new.html.erb
<div class="container">
  <h1>Projects#new</h1>
  <%= render "form" %>
</div>

app/views/projects/show.html.erb
<div class="col-md-12 col-sm-12 colcol-xs-12 blog-content">
  <h2 class="text-center"><%= @project.name %></h2>
  
  <!--div><%#= raw @project.details %></div-->
  <!--h5 class="text-center"><%#= @project.created_at.strftime('%b %d, %Y') %></h5-->
  <div><%= 'Updated: '+@project.updated_at.strftime('%b %d, %Y') %></div>
  <% if user_signed_in? %>
    <div class="links-show">
      <%= link_to 'Edit', edit_project_path(:id => @project) %> |
      <%= link_to 'Back', projects_path %>
    </div>
  <% end %>
  <%#= link_to 'Add New Sprint', new_project_sprint_path(@project), class: 'btn btn-primary', id: 'new_sprint' %>
  <div id="sprint-list"> <%= render 'sprints/sprints'%></div>
  <div id="form-sprints" class="center-div col-md-6 col-sm-6 col-xs-12">
  <%= render 'sprints/form'%>
  </div> 
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $( '#new_sprint' ).click(function(e) {
      e.preventDefault();
      $('#form-sprints').toggle('slow',function(){
      $('#sprint_name').focus();
      });  
    });
    var divWidth = $('.center-div').width();
    var windowWidth = $(window).width();
    $('#form-sprints').css({'left': (windowWidth-divWidth)/2 })
  });
</script>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>