config/routes.rb
Rails.application.routes.draw do
 

  mount Ckeditor::Engine => '/ckeditor'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'projects/index'

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }
  #devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  
  resources :projects do
    resources :sprints, :only => [:index,:show ,:new,:create ,:edit, :update, :destroy] do
      resources :tasks,:only => [:index,:show ,:new,:create ,:edit, :update, :destroy]
    end
  end
  put "/projects/:project_id/sprints/:sprint_id/tasks" => "tasks#change_stage"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agileboard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <!-- Custom Fonts -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  </head>

  <body >
   <!-- Navigation -->
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="#page-top">Agile Board</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <% if can? :manage, User %>
                    <li class=""><%= link_to '/admin', class: 'login-button' do %>Admin users<% end %></li>
                    <% end %>

                    <% if current_user.nil? %>
                    <li class=""><%= link_to new_user_session_path, class: 'login-button' do %>Sign in<% end %></li>
                    <% else %>
                      <li class=""><%= link_to projects_path, class: 'login-button' do %>Projects<% end %></li>
                    <% end %>

                    <% if user_signed_in? %>
                      <li class=""><%= link_to('Edit Profile', edit_user_registration_path) %></li>
                      <li class=""><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
                    <% else %>
                      <li class=""><%= link_to('Register', new_user_registration_path)  %></li>
                      <li class=""><%= link_to('Login', new_user_session_path)  %></li>  
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

	<% unless flash.empty? %>
	     <script type="text/javascript">
	          <% flash.each do |f| %>
		      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
		     	 toastr['<%= type %>']('<%= f[1] %>');
		   <% end %>
	     </script>
	<% end %>
  <div class="layout-Container scontainer">
    <%= yield %>
  </div>
  </body>
</html>